apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tiagovalentimbarreto/proshop-frontend
          env:
            - name: GET_HOSTS_FROM
              value: "dns"
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: frontend
