apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-minikube/*
build:
  local:
    push: false
  artifacts:
    - image: tiagovalentimbarreto/proshop-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: tiagovalentimbarreto/proshop-backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
