apiVersion: skaffold/v2beta16
kind: Config

build:
  local:
    push: false
  artifacts:
    - image: tiagovalentimbarreto/proshop-frontend
      context: frontend
      sync:
        infer: ['**/*']
      docker:
        dockerfile: Dockerfile

    - image: tiagovalentimbarreto/proshop-backend
      context: backend
      sync:
        infer: ['**/*']
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - ./infra/k8s-mkb/*
