apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
  namespace: default
data:
  ME_CONFIG_BASICAUTH_USERNAME: mongo-user
  ME_CONFIG_BASICAUTH_PASSWORD: MongoExpressPassword!
  ME_CONFIG_MONGODB_SERVER: mongo-service
  ME_CONFIG_MONGODB_PORT: "27017"
  ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDBPassword!

