name: deploy-backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t tiagovalentimbarreto/proshop-backend .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push tiagovalentimbarreto/ticketing-auth
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save ticketing-cluster
      # - run: kubectl rollout restart deployment auth-deploy

